// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsumeOpenSettingsRequest() {
  return window['go']['main']['App']['ConsumeOpenSettingsRequest']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function HandleGlobalHotkey() {
  return window['go']['main']['App']['HandleGlobalHotkey']();
}

export function HideMainWindow() {
  return window['go']['main']['App']['HideMainWindow']();
}

export function OpenSettingsWindow() {
  return window['go']['main']['App']['OpenSettingsWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SendPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2);
}

export function ShowLauncherWindow() {
  return window['go']['main']['App']['ShowLauncherWindow']();
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function TestTarget(arg1) {
  return window['go']['main']['App']['TestTarget'](arg1);
}

export function ToggleMainWindow() {
  return window['go']['main']['App']['ToggleMainWindow']();
}
