// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ConsumeOpenSettingsRequest():Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function GetTargets():Promise<Array<config.Target>>;

export function HandleGlobalHotkey():Promise<void>;

export function HideMainWindow():Promise<void>;

export function OpenSettingsWindow():Promise<void>;

export function Quit():Promise<void>;

export function ReloadConfig():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveWindowState():Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<config.SendPromptResult>;

export function ShowLauncherWindow():Promise<void>;

export function ShowMainWindow():Promise<void>;

export function TestTarget(arg1:string):Promise<void>;

export function ToggleMainWindow():Promise<void>;
